/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#596980",
        "on-primary-container": "#e3e6ff",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        "on-error": "#ffffff",
        "secondary": "#565e74",
        "on-tertiary-container": "#dbe9ff",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#434656",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "secondary-container": "#dae2fd",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "outline": "#737688",
        "surface-container": "#eceef0",
        "on-background": "#191c1e",
        "tertiary": "#415166",
        "primary-container": "#0055ff",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#b6c4ff",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#004dea",
        "on-tertiary-fixed-variant": "#38485d",
        "on-primary-fixed": "#001551",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "primary": "#0041c8",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed": "#d3e4fe",
        "secondary-fixed": "#dae2fd",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary-container": "#5c647a",
        "outline-variant": "#c3c5d9",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#0039b3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base-unit": "4px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max-width": "1280px"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist"],
        "label-sm": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "label-md": ["Geist"],
        "body-md": ["Geist"],
        "display-lg": ["Geist"],
        "body-lg": ["Geist"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
