export interface ActivityItem {
  id: string;
  title: string;
  description: string;
  price: number;
  rating: number;
  reviews: number;
  category: string;
  location: string;
  destination: string;
  duration: string;
  image: string;
  time: string;
  note: string;
  tier: 'must' | 'popular' | 'extended';
  icon: string;
}

export interface CityDestination {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  flag: string;
  region: string;
  image: string;
  description: string;
  activities: ActivityItem[];
}

export const DESTINATION_DATA: Record<string, CityDestination> = {
  Goa: {
    id: "dest-goa",
    name: "Goa",
    country: "India",
    countryCode: "IN",
    flag: "🇮🇳",
    region: "South Asia",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&auto=format&fit=crop",
    description: "Sun, sand & seafood on India's most iconic beach destination.",
    activities: [
      {
        id: "goa-1",
        title: "Baga Beach Shack Dinner & Sunset",
        description: "Enjoy fresh Arabian Sea seafood, candlelit beach tables, live Goan music, and chilled tender coconut as the sun dips below the ocean horizon at Baga Beach.",
        price: 800,
        rating: 4.8,
        reviews: 185,
        category: "Food",
        location: "Goa, India",
        destination: "Goa",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500",
        time: "07:00 PM",
        note: "Fresh catch of the day, best enjoyed at sunset",
        tier: "must",
        icon: "restaurant"
      },
      {
        id: "goa-2",
        title: "Parasailing at Calangute Beach",
        description: "Experience high-adrenaline water sports soaring above Calangute coastline with professional instructors and safety equipment included.",
        price: 1200,
        rating: 4.9,
        reviews: 210,
        category: "Water Sports",
        location: "Goa, India",
        destination: "Goa",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500",
        time: "10:00 AM",
        note: "High-adrenaline water sports, 15-min session",
        tier: "must",
        icon: "paragliding"
      },
      {
        id: "goa-3",
        title: "Old Goa Portuguese Churches Heritage Tour",
        description: "Guided walking tour through UNESCO World Heritage sites including Sé Cathedral, Basilica of Bom Jesus, and St. Augustine tower in Old Goa.",
        price: 300,
        rating: 4.7,
        reviews: 145,
        category: "Culture",
        location: "Goa, India",
        destination: "Goa",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=500",
        time: "09:00 AM",
        note: "Sé Cathedral & Basilica of Bom Jesus — UNESCO Heritage",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "goa-4",
        title: "Dolphin Watching Boat Cruise",
        description: "Scenic early morning cruise along Sinquerim river mouth to spot playful Indo-Pacific humpback dolphins in their natural habitat.",
        price: 600,
        rating: 4.6,
        reviews: 120,
        category: "Water Sports",
        location: "Goa, India",
        destination: "Goa",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=500",
        time: "07:30 AM",
        note: "Early morning cruise — sightings nearly guaranteed",
        tier: "popular",
        icon: "sailing"
      },
      {
        id: "goa-5",
        title: "Anjuna Flea Market Browse & Shopping",
        description: "Browse hundreds of colorful beachside stalls selling spices, breezy cotton clothes, handmade jewellery, leather crafts, and Goan souvenirs.",
        price: 400,
        rating: 4.7,
        reviews: 160,
        category: "Culture",
        location: "Goa, India",
        destination: "Goa",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500",
        time: "10:00 AM",
        note: "Wednesday market — spices, clothes, crafts",
        tier: "popular",
        icon: "shopping_bag"
      },
      {
        id: "goa-6",
        title: "Dudhsagar Waterfalls Jeep Safari & Trek",
        description: "Jeep safari through Bhagwan Mahavir Wildlife Sanctuary to the four-tiered white milk waterfall, with freshwater pool swimming included.",
        price: 1500,
        rating: 4.9,
        reviews: 310,
        category: "Adventure",
        location: "Goa, India",
        destination: "Goa",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=500",
        time: "06:00 AM",
        note: "Jeep safari + waterfall trek combo — full day",
        tier: "extended",
        icon: "landscape"
      },
      {
        id: "goa-7",
        title: "Fort Aguada & Lighthouse Sunset Walk",
        description: "Explore the 17th-century Portuguese fortress overlooking Mandovi river and Arabian sea, featuring a historic four-storey lighthouse.",
        price: 150,
        rating: 4.8,
        reviews: 240,
        category: "Sightseeing",
        location: "Goa, India",
        destination: "Goa",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=500",
        time: "05:00 PM",
        note: "17th-century Portuguese fort with panoramic sea views",
        tier: "popular",
        icon: "explore"
      },
      {
        id: "goa-8",
        title: "Sahakari Spice Farm Tour & Traditional Lunch",
        description: "Walk through lush organic spice plantations in Ponda, taste fresh cardamom and cinnamon tea, and relish an authentic banana-leaf Goan buffet.",
        price: 800,
        rating: 4.9,
        reviews: 175,
        category: "Food",
        location: "Goa, India",
        destination: "Goa",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500",
        time: "11:00 AM",
        note: "Organic spice plantation tour + traditional Goan lunch included",
        tier: "extended",
        icon: "eco"
      }
    ]
  },

  Jaipur: {
    id: "dest-jaipur",
    name: "Jaipur",
    country: "India",
    countryCode: "IN",
    flag: "🇮🇳",
    region: "Rajasthan",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&auto=format&fit=crop",
    description: "The Pink City — royal palaces, majestic forts & colourful bazaars.",
    activities: [
      {
        id: "jai-1",
        title: "Amber Fort & Sheesh Mahal Guided Tour",
        description: "Explore the hilltop Amber Fort with an expert historian, visiting the Mirror Palace (Sheesh Mahal), royal courtyards, and Maota lake vistas.",
        price: 500,
        rating: 4.9,
        reviews: 285,
        category: "Culture",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500",
        time: "09:00 AM",
        note: "Arrive early to beat crowds; audio guide recommended",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "jai-2",
        title: "City Palace Museum & Chandra Mahal Visit",
        description: "Step into the royal residence of the Maharaja of Jaipur, featuring magnificent peacock courtyards, royal costumes, and historic weapons.",
        price: 400,
        rating: 4.8,
        reviews: 210,
        category: "Culture",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1603269235296-919502693892?w=500",
        time: "10:30 AM",
        note: "Royal residence with 7 courtyards — royal armoury included",
        tier: "must",
        icon: "museum"
      },
      {
        id: "jai-3",
        title: "Hawa Mahal Palace of Winds Photo Stop",
        description: "Photograph the iconic 953 honeycomb windows of Hawa Mahal built for royal ladies to observe street festivals without being seen.",
        price: 150,
        rating: 4.9,
        reviews: 340,
        category: "Sightseeing",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1624461877478-f716616eb883?w=500",
        time: "08:00 AM",
        note: "Best photographed at sunrise from the street",
        tier: "must",
        icon: "photo_camera"
      },
      {
        id: "jai-4",
        title: "Chokhi Dhani Ethnic Rajasthani Dinner",
        description: "Immerse in a traditional village resort featuring puppet shows, Kalbelia folk dances, camel rides, and unlimited Rajasthani Dal Baati Churma thali.",
        price: 900,
        rating: 4.8,
        reviews: 290,
        category: "Food",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=500",
        time: "06:00 PM",
        note: "Rajasthani thali + folk dance & puppet show",
        tier: "must",
        icon: "restaurant"
      },
      {
        id: "jai-5",
        title: "Johri Bazaar & Bapu Bazaar Gem Shopping",
        description: "Bargain through narrow pink lanes for authentic Kundan jewellery, Jaipur blue pottery, bandhani dupattas, and handcrafted leather juttis.",
        price: 300,
        rating: 4.7,
        reviews: 180,
        category: "Culture",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1601058268499-e52658b8bb88?w=500",
        time: "11:00 AM",
        note: "Best deals on precious stones & Rajasthani crafts",
        tier: "popular",
        icon: "diamond"
      },
      {
        id: "jai-6",
        title: "Nahargarh Fort Sunset Panorama",
        description: "Perched high on the Aravalli hills, watch the entire Pink City turn golden as dusk settles over Jaipur's historic ramparts.",
        price: 200,
        rating: 4.9,
        reviews: 220,
        category: "Sightseeing",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1572587353427-442b334bc915?w=500",
        time: "04:30 PM",
        note: "Panoramic view of entire Jaipur at dusk",
        tier: "popular",
        icon: "landscape"
      },
      {
        id: "jai-7",
        title: "Jantar Mantar UNESCO Astronomical Observatory",
        description: "Marvel at 19 architectural astronomy instruments built by Maharaja Sawai Jai Singh II, featuring the world's largest stone sundial.",
        price: 250,
        rating: 4.8,
        reviews: 165,
        category: "Culture",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=500",
        time: "10:00 AM",
        note: "UNESCO-listed 18th-century stone observatory",
        tier: "popular",
        icon: "explore"
      },
      {
        id: "jai-8",
        title: "Sanganeri Block Printing Craft Workshop",
        description: "Hands-on artisan workshop learning carved wooden block printing on cotton fabric using natural vegetable dyes, and take your creation home.",
        price: 600,
        rating: 4.9,
        reviews: 110,
        category: "Culture",
        location: "Jaipur, India",
        destination: "Jaipur",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500",
        time: "11:00 AM",
        note: "Learn traditional Sanganer block printing technique",
        tier: "extended",
        icon: "brush"
      }
    ]
  },

  Tokyo: {
    id: "dest-tokyo",
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    region: "East Asia",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600&auto=format&fit=crop",
    description: "Neon-lit megacity blending ancient temples with cutting-edge tech.",
    activities: [
      {
        id: "tky-1",
        title: "Senso-ji Temple & Asakusa Historic Stroll",
        description: "Tokyo's oldest Buddhist temple. Enter through Kaminarimon Gate with giant red lanterns, stroll Nakamise shopping street, and try fresh senbei rice crackers.",
        price: 0,
        rating: 4.9,
        reviews: 420,
        category: "Culture",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=500",
        time: "08:00 AM",
        note: "Free entry — visit before 9 AM to avoid crowds",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "tky-2",
        title: "Shibuya Scramble Crossing & Hachiko Statue",
        description: "Cross the busiest pedestrian intersection in the world where up to 3,000 people cross at once, and visit the faithful Hachiko dog monument.",
        price: 0,
        rating: 4.9,
        reviews: 580,
        category: "Sightseeing",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=500",
        time: "06:00 PM",
        note: "World's busiest pedestrian crossing — free landmark",
        tier: "must",
        icon: "photo_camera"
      },
      {
        id: "tky-3",
        title: "Tokyo Tower Main Deck Sunset View",
        description: "Iconic 333-meter Eiffel Tower-inspired red tower offering panoramic views of Tokyo skyline and distant Mount Fuji on clear days (1,200 JPY ≈ ₹660).",
        price: 660,
        rating: 4.8,
        reviews: 310,
        category: "Sightseeing",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=500",
        time: "07:00 PM",
        note: "Night view of Mt. Fuji on clear winter evenings",
        tier: "must",
        icon: "landscape"
      },
      {
        id: "tky-4",
        title: "Tsukiji Outer Market Fresh Seafood Breakfast",
        description: "Sample fresh fatty tuna nigiri, tamagoyaki rolled omlettes, grilled scallops, and wagyu beef skewers in Tokyo's historic culinary district (~2,000 JPY ≈ ₹1,100).",
        price: 1100,
        rating: 4.9,
        reviews: 290,
        category: "Food",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500",
        time: "07:00 AM",
        note: "Fresh sushi, tamagoyaki, matcha — Tokyo's foodie paradise",
        tier: "must",
        icon: "restaurant"
      },
      {
        id: "tky-5",
        title: "teamLab Planets Digital Art Museum",
        description: "Wade barefoot through knee-deep water mirror rooms and immersive digital universe of light and crystal universes (3,800 JPY ≈ ₹2,100).",
        price: 2100,
        rating: 5.0,
        reviews: 650,
        category: "Culture",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500",
        time: "10:00 AM",
        note: "Book 2–3 weeks in advance — sells out quickly",
        tier: "popular",
        icon: "palette"
      },
      {
        id: "tky-6",
        title: "Shinjuku Gyoen National Garden Walk",
        description: "Tranquil 144-acre sanctuary blending traditional Japanese landscape gardens, English landscape, and French formal gardens (500 JPY ≈ ₹275).",
        price: 275,
        rating: 4.8,
        reviews: 240,
        category: "Sightseeing",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1583845112239-97ef1341b271?w=500",
        time: "09:00 AM",
        note: "Cherry blossom & autumn foliage highlight",
        tier: "popular",
        icon: "eco"
      },
      {
        id: "tky-7",
        title: "Harajuku Takeshita Street & Kawaii Walk",
        description: "Explore youth fashion, rainbow cotton candy, monster cafes, crepe stands, and vintage clothing boutiques along Takeshita Dori (~1,000 JPY ≈ ₹550).",
        price: 550,
        rating: 4.7,
        reviews: 310,
        category: "Culture",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500",
        time: "12:00 PM",
        note: "Crepes, quirky fashion, cosplay culture",
        tier: "popular",
        icon: "shopping_bag"
      },
      {
        id: "tky-8",
        title: "Akihabara Electric Town & Anime Arcade Tour",
        description: "Dive into 8-story anime mega-stores, retro gaming arcades at Super Potato, gachapon machines, and maid cafe pop culture (~1,500 JPY ≈ ₹825).",
        price: 825,
        rating: 4.8,
        reviews: 380,
        category: "Culture",
        location: "Tokyo, Japan",
        destination: "Tokyo",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1563089145-599997674d42?w=500",
        time: "02:00 PM",
        note: "Multi-floor electronics, manga, figurines & arcade gaming",
        tier: "extended",
        icon: "videogame_asset"
      }
    ]
  },

  Paris: {
    id: "dest-paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    flag: "🇫🇷",
    region: "Western Europe",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&auto=format&fit=crop",
    description: "City of Love — world-class art, haute cuisine & the Eiffel Tower.",
    activities: [
      {
        id: "par-1",
        title: "Eiffel Tower Skip-the-Line Summit Access",
        description: "Bypass queue lines to ascend to the top 276-meter observation deck of the Eiffel Tower for unparalleled views of Paris landmarks (35 EUR ≈ ₹3,150).",
        price: 3150,
        rating: 4.9,
        reviews: 540,
        category: "Sightseeing",
        location: "Paris, France",
        destination: "Paris",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=500",
        time: "09:00 AM",
        note: "Book 3 weeks ahead — 3rd floor for best panoramic views",
        tier: "must",
        icon: "landscape"
      },
      {
        id: "par-2",
        title: "Louvre Museum Guided Masterpieces Tour",
        description: "Bypass the main queue lines with an expert art historian to view Mona Lisa, Venus de Milo, Winged Victory of Samothrace, and crown jewels (22 EUR ≈ ₹1,980).",
        price: 1980,
        rating: 4.9,
        reviews: 610,
        category: "Culture",
        location: "Paris, France",
        destination: "Paris",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=500",
        time: "10:00 AM",
        note: "Mona Lisa + Venus de Milo — arrive at opening time",
        tier: "must",
        icon: "museum"
      },
      {
        id: "par-3",
        title: "Seine River Evening Sunset Cruise",
        description: "Glide past Notre-Dame Cathedral, Musée d'Orsay, and sparkling Eiffel Tower while enjoying French wine and recorded commentary (18 EUR ≈ ₹1,620).",
        price: 1620,
        rating: 4.8,
        reviews: 380,
        category: "Sightseeing",
        location: "Paris, France",
        destination: "Paris",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1509299349698-ab22323ae696?w=500",
        time: "08:00 PM",
        note: "Illuminated Paris at night — romantic & iconic",
        tier: "must",
        icon: "sailing"
      },
      {
        id: "par-4",
        title: "Montmartre & Sacré-Cœur Basilica Walk",
        description: "Wander bohemian cobbled streets where Picasso and Van Gogh painted, visit Place du Tertre artists, and take in Sacré-Cœur panoramic views.",
        price: 0,
        rating: 4.8,
        reviews: 290,
        category: "Culture",
        location: "Paris, France",
        destination: "Paris",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=500",
        time: "10:00 AM",
        note: "Free entry — artist quarter & best city panorama",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "par-5",
        title: "Palace of Versailles Hall of Mirrors Day Pass",
        description: "Travel by train to Louis XIV's magnificent royal palace. Tour Hall of Mirrors, king's grand apartments, and fountain gardens (26 EUR ≈ ₹2,340).",
        price: 2340,
        rating: 4.9,
        reviews: 410,
        category: "Culture",
        location: "Paris, France",
        destination: "Paris",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1591557304122-01968846c4f0?w=500",
        time: "09:00 AM",
        note: "Full-day trip — gardens + Hall of Mirrors",
        tier: "popular",
        icon: "villa"
      },
      {
        id: "par-6",
        title: "French Patisserie Croissant & Macaron Tour",
        description: "Guided food tasting walk through Saint-Germain-des-Prés visiting legendary boulangeries to sample warm baguettes and macarons (20 EUR ≈ ₹1,800).",
        price: 1800,
        rating: 4.9,
        reviews: 195,
        category: "Food",
        location: "Paris, France",
        destination: "Paris",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500",
        time: "09:00 AM",
        note: "Croissants, macarons, éclairs at legendary boulangeries",
        tier: "popular",
        icon: "restaurant"
      },
      {
        id: "par-7",
        title: "Musée d'Orsay Impressionist Art Masterpieces",
        description: "Set inside a grand 1900 Beaux-Arts railway station, marvel at world's largest collection of Impressionist paintings by Monet and Degas (16 EUR ≈ ₹1,440).",
        price: 1440,
        rating: 4.8,
        reviews: 320,
        category: "Culture",
        location: "Paris, France",
        destination: "Paris",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1584478898184-b57f21c4b2ed?w=500",
        time: "11:00 AM",
        note: "Monet, Renoir, Van Gogh — lighter crowds than Louvre",
        tier: "popular",
        icon: "palette"
      },
      {
        id: "par-8",
        title: "Le Marais Historic District & Falafel Walk",
        description: "Discover trendy Marais quarter with 17th-century aristocratic mansions, Place des Vosges, falafel spots on Rue des Rosiers (12 EUR ≈ ₹1,080).",
        price: 1080,
        rating: 4.7,
        reviews: 150,
        category: "Culture",
        location: "Paris, France",
        destination: "Paris",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=500",
        time: "12:00 PM",
        note: "Falafel, fashion boutiques & historic synagogues",
        tier: "extended",
        icon: "explore"
      }
    ]
  },

  Rome: {
    id: "dest-rome",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    flag: "🇮🇹",
    region: "Southern Europe",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&auto=format&fit=crop",
    description: "The Eternal City — ancient ruins, Vatican glory & world-class pizza.",
    activities: [
      {
        id: "rom-1",
        title: "Colosseum & Roman Forum VIP Underground Tour",
        description: "Walk the arena floor where gladiators fought, descend into underground chambers, and tour Palatine Hill with a Roman archaeologist (24 EUR ≈ ₹2,160).",
        price: 2160,
        rating: 4.9,
        reviews: 490,
        category: "Culture",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=500",
        time: "09:00 AM",
        note: "Must book skip-line entry — gladiator arena + ancient forum",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "rom-2",
        title: "Vatican Museums & Sistine Chapel Early Access",
        description: "Early morning access to St. Peter's Basilica, Raphael Rooms, and Michelangelo's famous Sistine Chapel ceiling fresco (28 EUR ≈ ₹2,520).",
        price: 2520,
        rating: 4.9,
        reviews: 520,
        category: "Culture",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=500",
        time: "08:00 AM",
        note: "Michelangelo's ceiling — allow 2–3 hours minimum",
        tier: "must",
        icon: "museum"
      },
      {
        id: "rom-3",
        title: "Trastevere Neighbourhood Dinner & Wine Crawl",
        description: "Stroll cobble-paved Trastevere district to dine at local trattorias for authentic pasta carbonara, cacio e pepe, and Chianti wine (22 EUR ≈ ₹1,980).",
        price: 1980,
        rating: 4.8,
        reviews: 310,
        category: "Food",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=500",
        time: "07:00 PM",
        note: "Best pasta carbonara & cacio e pepe in Rome",
        tier: "must",
        icon: "restaurant"
      },
      {
        id: "rom-4",
        title: "Trevi Fountain Coin Toss & Artisanal Gelato",
        description: "Toss a coin over your left shoulder into Baroque Trevi Fountain to guarantee your return to Rome, followed by organic gelato (5 EUR ≈ ₹450).",
        price: 450,
        rating: 4.9,
        reviews: 430,
        category: "Sightseeing",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1525874684015-5837e263121c?w=500",
        time: "08:00 AM",
        note: "Toss a coin for luck — go at dawn to avoid crowds",
        tier: "must",
        icon: "photo_camera"
      },
      {
        id: "rom-5",
        title: "Castel Sant'Angelo Papal Fortress Tour",
        description: "Explore Emperor Hadrian's mausoleum turned papal fortress with secret escape corridors to the Vatican and Tiber views (15 EUR ≈ ₹1,350).",
        price: 1350,
        rating: 4.7,
        reviews: 180,
        category: "Culture",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1529260830199-42c24126f198?w=500",
        time: "02:00 PM",
        note: "Former papal fortress with incredible Tiber River views",
        tier: "popular",
        icon: "castle"
      },
      {
        id: "rom-6",
        title: "Authentic Roman Pasta & Gelato Cooking Class",
        description: "Hands-on culinary class in a Roman home kitchen making fresh egg fettuccine dough, classic sauces, and Italian gelato (45 EUR ≈ ₹4,050).",
        price: 4050,
        rating: 4.9,
        reviews: 240,
        category: "Food",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500",
        time: "11:00 AM",
        note: "Small group, hands-on cooking + wine pairing lunch",
        tier: "popular",
        icon: "school"
      },
      {
        id: "rom-7",
        title: "Campo de' Fiori Morning Open Air Market",
        description: "Experience Rome's oldest bustling open market filled with fresh pecorino cheese, truffles, balsamic vinegar, olive oil, and flowers (6 EUR ≈ ₹540).",
        price: 540,
        rating: 4.6,
        reviews: 140,
        category: "Food",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=500",
        time: "08:00 AM",
        note: "Flowers, produce, spices — lively Rome morning market",
        tier: "popular",
        icon: "local_florist"
      },
      {
        id: "rom-8",
        title: "Borghese Gallery Bernini Sculptures Tour",
        description: "Marvel at Bernini's master marble masterpieces Apollo and Daphne, Caravaggio paintings, and Canova sculptures inside Villa Borghese (18 EUR ≈ ₹1,620).",
        price: 1620,
        rating: 4.9,
        reviews: 210,
        category: "Culture",
        location: "Rome, Italy",
        destination: "Rome",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=500",
        time: "09:00 AM",
        note: "Bernini sculptures — reservation is mandatory",
        tier: "extended",
        icon: "palette"
      }
    ]
  },

  Bangkok: {
    id: "dest-bangkok",
    name: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    flag: "🇹🇭",
    region: "Southeast Asia",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&auto=format&fit=crop",
    description: "Street food paradise with golden temples, tuk-tuks & night markets.",
    activities: [
      {
        id: "bkk-1",
        title: "Grand Palace & Emerald Buddha Guided Tour",
        description: "Tour the gold-spired complex of the Thai King's court, featuring the sacred 14th-century Emerald Buddha (500 THB ≈ ₹1,200).",
        price: 1200,
        rating: 4.8,
        reviews: 350,
        category: "Culture",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=500",
        time: "08:30 AM",
        note: "Dress modestly (no shorts/sleeveless) — arrive early",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "bkk-2",
        title: "Wat Arun Temple of Dawn Sunset View",
        description: "Climb the porcelain-encrusted central prang of Wat Arun temple situated on Chao Phraya riverbank for sunset river photos (100 THB ≈ ₹240).",
        price: 240,
        rating: 4.9,
        reviews: 290,
        category: "Culture",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1540611025311-01df3cef54b5?w=500",
        time: "05:00 PM",
        note: "Spectacular at sunset — porcelain-encrusted spires",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "bkk-3",
        title: "Chao Phraya River Dinner Cruise & Live Music",
        description: "Buffet seafood dinner aboard a luxury riverboat listening to live saxophonists as illuminated Bangkok temples pass by (1,200 THB ≈ ₹2,880).",
        price: 2880,
        rating: 4.7,
        reviews: 260,
        category: "Food",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=500",
        time: "07:30 PM",
        note: "Buffet dinner + live music + illuminated temple views",
        tier: "must",
        icon: "sailing"
      },
      {
        id: "bkk-4",
        title: "Chatuchak Weekend Market Exploration",
        description: "Explore 15,000 stalls packed across 35 acres selling Thai silk, coconut ice cream, wooden carvings, and vintage fashion (200 THB ≈ ₹480).",
        price: 480,
        rating: 4.8,
        reviews: 320,
        category: "Culture",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500",
        time: "10:00 AM",
        note: "15,000 stalls — fashion, antiques, street food, plants",
        tier: "must",
        icon: "shopping_bag"
      },
      {
        id: "bkk-5",
        title: "Michelin Street Food & Tuk-Tuk Midnight Crawl",
        description: "Hop in an electric neon tuk-tuk to sample Michelin Bib Gourmand Pad Thai, crab omelettes, crab fried rice, and mango sticky rice (600 THB ≈ ₹1,440).",
        price: 1440,
        rating: 4.9,
        reviews: 280,
        category: "Food",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500",
        time: "06:00 PM",
        note: "Pad Thai, mango sticky rice, papaya salad — local guide",
        tier: "popular",
        icon: "restaurant"
      },
      {
        id: "bkk-6",
        title: "Muay Thai Boxing Fight Night Championship",
        description: "Ringside stadium seats at Rajadamnern Stadium witnessing authentic Thai kickboxing matches accompanied by live Sarama music (1,000 THB ≈ ₹2,400).",
        price: 2400,
        rating: 4.8,
        reviews: 175,
        category: "Culture",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1517649763962-0c6232661a0b?w=500",
        time: "06:00 PM",
        note: "Ringside seats at Rajadamnern Stadium",
        tier: "popular",
        icon: "sports_martial_arts"
      },
      {
        id: "bkk-7",
        title: "Sompong Authentic Thai Cooking Class",
        description: "Visit Khlong Toei fresh food market then cook 4 classic dishes including Tom Yum Goong and Green Curry in a culinary studio (1,000 THB ≈ ₹2,400).",
        price: 2400,
        rating: 4.9,
        reviews: 210,
        category: "Food",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=500",
        time: "10:00 AM",
        note: "Market visit + cook 4 dishes + take-home recipe book",
        tier: "popular",
        icon: "school"
      },
      {
        id: "bkk-8",
        title: "Damnoen Saduak & Railway Market Day Trip",
        description: "Watch the Maeklong train pass inches from vegetable stalls, then ride a paddle boat along canal floating markets (600 THB ≈ ₹1,440).",
        price: 1440,
        rating: 4.7,
        reviews: 230,
        category: "Adventure",
        location: "Bangkok, Thailand",
        destination: "Bangkok",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=500",
        time: "07:00 AM",
        note: "Early start to see vendors before afternoon crowds arrive",
        tier: "extended",
        icon: "explore"
      }
    ]
  },

  Dubai: {
    id: "dest-dubai",
    name: "Dubai",
    country: "UAE",
    countryCode: "AE",
    flag: "🇦🇪",
    region: "Middle East",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&auto=format&fit=crop",
    description: "Ultramodern skyline, desert dunes, luxury malls & world records.",
    activities: [
      {
        id: "dxb-1",
        title: "Burj Khalifa At the Top (124th & 125th Floor)",
        description: "Ride the world's fastest elevator to 452 meters altitude for panoramic vistas of Dubai Marina, Palm Jumeirah, and Persian Gulf (179 AED ≈ ₹4,025).",
        price: 4025,
        rating: 4.9,
        reviews: 580,
        category: "Sightseeing",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=500",
        time: "06:00 PM",
        note: "Book sunset slot — views extend to Iran on clear days",
        tier: "must",
        icon: "landscape"
      },
      {
        id: "dxb-2",
        title: "Desert Safari Dune Bashing, Quad Bike & BBQ",
        description: "Thrilling 4x4 dune bashing across Lahbab red sand dunes, camel rides, sandboarding, falconry photos, and Bedouin camp dinner (150 AED ≈ ₹3,375).",
        price: 3375,
        rating: 4.9,
        reviews: 620,
        category: "Adventure",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500",
        time: "03:30 PM",
        note: "Dune bashing, camel ride, henna, belly dance + BBQ dinner",
        tier: "must",
        icon: "terrain"
      },
      {
        id: "dxb-3",
        title: "Dubai Mall Fountain Show & Lake Ride",
        description: "Watch the world's largest dancing fountain light show set to classical and Arabic music at the foot of Burj Khalifa tower.",
        price: 0,
        rating: 4.8,
        reviews: 490,
        category: "Sightseeing",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1546412414-8035e1776c9a?w=500",
        time: "08:00 PM",
        note: "Free show every 30 mins after 6 PM — world's largest fountain",
        tier: "must",
        icon: "water"
      },
      {
        id: "dxb-4",
        title: "Old Dubai Creek Wooden Abra Boat & Gold Souk",
        description: "Cross historic Dubai Creek on a traditional wooden abra boat to wander through scented Spice Souk and glittering Gold Souk markets (10 AED ≈ ₹225).",
        price: 225,
        rating: 4.7,
        reviews: 290,
        category: "Culture",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1578895210405-907db48a7812?w=500",
        time: "10:00 AM",
        note: "Wooden abra boat crossing + Gold & Spice Souks",
        tier: "must",
        icon: "sailing"
      },
      {
        id: "dxb-5",
        title: "Atlantis Aquaventure Waterpark Full-Day Pass",
        description: "Experience 105 world-record water slides, shark tunnel drop slides, lazy river rapids, and private beach access at Atlantis Palm (345 AED ≈ ₹7,760).",
        price: 7760,
        rating: 4.9,
        reviews: 380,
        category: "Water Sports",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500",
        time: "10:00 AM",
        note: "Full-day entry — Leap of Faith slide is unmissable",
        tier: "popular",
        icon: "pool"
      },
      {
        id: "dxb-6",
        title: "La Mer Beachfront & JBR Walk Stroll",
        description: "Trendy coastal district featuring colorful wooden cabanas, street art murals, beachfront dining, and views of Ain Dubai Ferris Wheel.",
        price: 0,
        rating: 4.7,
        reviews: 210,
        category: "Sightseeing",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=500",
        time: "05:00 PM",
        note: "Free beach — boutiques, restaurants & stunning sea views",
        tier: "popular",
        icon: "beach_access"
      },
      {
        id: "dxb-7",
        title: "Dubai Frame Glass Skywalk Tour",
        description: "Walk across a 93-meter glass bridge linking 150-meter towers with Old Dubai views on one side and futuristic downtown Dubai on the other (50 AED ≈ ₹1,125).",
        price: 1125,
        rating: 4.8,
        reviews: 310,
        category: "Sightseeing",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=500",
        time: "11:00 AM",
        note: "Glass sky bridge between old and new Dubai halves",
        tier: "popular",
        icon: "window"
      },
      {
        id: "dxb-8",
        title: "Dubai Miracle Garden Floral Sculptures",
        description: "World's largest natural flower garden featuring 150 million blooming flowers transformed into giant castles and Emirates A380 planes (95 AED ≈ ₹2,135).",
        price: 2135,
        rating: 4.8,
        reviews: 270,
        category: "Sightseeing",
        location: "Dubai, UAE",
        destination: "Dubai",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500",
        time: "10:00 AM",
        note: "World's largest natural flower garden (Oct–Apr season only)",
        tier: "extended",
        icon: "local_florist"
      }
    ]
  },

  Bali: {
    id: "dest-bali",
    name: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    flag: "🇮🇩",
    region: "Southeast Asia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&auto=format&fit=crop",
    description: "Island of the Gods — rice terraces, surf, temples & wellness retreats.",
    activities: [
      {
        id: "bal-1",
        title: "Tanah Lot Sea Temple Sunset View",
        description: "Watch waves crash against the ancient 16th-century offshore rock temple dedicated to sea gods during Bali's iconic orange sunset (75,000 IDR ≈ ₹400).",
        price: 400,
        rating: 4.9,
        reviews: 410,
        category: "Culture",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=500",
        time: "05:00 PM",
        note: "Most photographed spot in Bali — dramatic ocean-rock temple",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "bal-2",
        title: "Ubud Sacred Monkey Forest Sanctuary",
        description: "Walk shaded rainforest paths surrounded by 700 friendly long-tailed macaques and moss-covered 14th-century Hindu stone temples (80,000 IDR ≈ ₹425).",
        price: 425,
        rating: 4.8,
        reviews: 480,
        category: "Sightseeing",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1540573133985-778788177695?w=500",
        time: "09:00 AM",
        note: "Over 700 macaque monkeys in ancient forest temple",
        tier: "must",
        icon: "forest"
      },
      {
        id: "bal-3",
        title: "Tegalalang Rice Terraces & Jungle Walk",
        description: "Hike emerald green stepped paddy fields in Ubud, meet traditional subak irrigation farmers, and sample fresh coconut water (50,000 IDR ≈ ₹265).",
        price: 265,
        rating: 4.9,
        reviews: 520,
        category: "Sightseeing",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=500",
        time: "08:00 AM",
        note: "Iconic jungle swing photo — go very early to avoid crowds",
        tier: "must",
        icon: "landscape"
      },
      {
        id: "bal-4",
        title: "Uluwatu Cliffside Kecak Fire Dance",
        description: "Choral performance by 50 chanting men telling Ramayana legends set on a 70-meter limestone cliff overlooking crashing ocean (150,000 IDR ≈ ₹795).",
        price: 795,
        rating: 4.9,
        reviews: 380,
        category: "Culture",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=500",
        time: "06:00 PM",
        note: "Uluwatu cliffside sunset performance — absolutely spectacular",
        tier: "must",
        icon: "theater_comedy"
      },
      {
        id: "bal-5",
        title: "Ubud Bali Giant Jungle Swing",
        description: "Soar high over tropical river palm valleys on a 78-meter high safety-harnessed swing with woven bird nest photo ops (200,000 IDR ≈ ₹1,060).",
        price: 1060,
        rating: 4.8,
        reviews: 290,
        category: "Adventure",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=500",
        time: "09:00 AM",
        note: "Swing over jungle valley — height up to 78 m",
        tier: "popular",
        icon: "accessibility"
      },
      {
        id: "bal-6",
        title: "Ubud Organic Farm Culinary Cooking Class",
        description: "Harvest organic herbs from traditional family compound garden to cook Satay Lilit, Nasi Goreng, and Sambal Matah (350,000 IDR ≈ ₹1,855).",
        price: 1855,
        rating: 4.9,
        reviews: 195,
        category: "Food",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500",
        time: "10:00 AM",
        note: "Market tour + cook 8 dishes + take-home recipe booklet",
        tier: "popular",
        icon: "school"
      },
      {
        id: "bal-7",
        title: "Kuta Beach Beginner Surfing Lesson",
        description: "Learn to catch your first ocean waves with a dedicated surf coach on soft sandy bottom waters, surfboard included (250,000 IDR ≈ ₹1,325).",
        price: 1325,
        rating: 4.8,
        reviews: 210,
        category: "Water Sports",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=500",
        time: "08:00 AM",
        note: "2-hr beginner lesson — boards & instructor included",
        tier: "popular",
        icon: "surfing"
      },
      {
        id: "bal-8",
        title: "Mount Batur Sunrise Volcano Trek & Hot Springs",
        description: "Early morning 1,717-meter active volcano hike to watch sunrise over Lake Batur, followed by volcanic hot spring bath (400,000 IDR ≈ ₹2,120).",
        price: 2120,
        rating: 4.9,
        reviews: 320,
        category: "Adventure",
        location: "Bali, Indonesia",
        destination: "Bali",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=500",
        time: "02:00 AM",
        note: "Active volcano trek — breakfast at summit, guide included",
        tier: "extended",
        icon: "hiking"
      }
    ]
  },

  Barcelona: {
    id: "dest-barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    flag: "🇪🇸",
    region: "Southern Europe",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efedd?w=600&auto=format&fit=crop",
    description: "Gaudí's dreamland — beach, tapas, Gothic Quarter & surreal architecture.",
    activities: [
      {
        id: "bcn-1",
        title: "Sagrada Família Cathedral & Tower Access",
        description: "Tour Antoni Gaudí's magnificent unfinished UNESCO basilica, admiring forest-like stained glass columns and Nativity tower views (26 EUR ≈ ₹2,340).",
        price: 2340,
        rating: 4.9,
        reviews: 580,
        category: "Culture",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1548625361-185b9b8b0e77?w=500",
        time: "09:00 AM",
        note: "Gaudí's masterpiece — must pre-book tower access",
        tier: "must",
        icon: "account_balance"
      },
      {
        id: "bcn-2",
        title: "Park Güell Mosaic Gardens Guided Tour",
        description: "Stroll through Gaudí's whimsical park to see the colorful ceramic salamander (El Drac), serpentine benches, and Mediterranean vistas (10 EUR ≈ ₹900).",
        price: 900,
        rating: 4.8,
        reviews: 410,
        category: "Sightseeing",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=500",
        time: "07:30 AM",
        note: "Limited timed slots — mosaic terrace is the highlight",
        tier: "must",
        icon: "landscape"
      },
      {
        id: "bcn-3",
        title: "La Boqueria Market Tapas & Sangria Tasting",
        description: "Taste freshly carved Jamón Ibérico de Bellota, Manchego cheeses, patatas bravas, croquetas, and fresh sangria in Mercat de la Boqueria (16 EUR ≈ ₹1,440).",
        price: 1440,
        rating: 4.9,
        reviews: 320,
        category: "Food",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1511527656417-089565a5e615?w=500",
        time: "10:00 AM",
        note: "World-famous covered food market on Las Ramblas",
        tier: "must",
        icon: "restaurant"
      },
      {
        id: "bcn-4",
        title: "Gothic Quarter & Roman Wall Walking Tour",
        description: "Wander 2,000-year-old narrow lanes of Barri Gòtic, visiting Barcelona Cathedral, Augustus Roman temple columns, and hidden plazas (8 EUR ≈ ₹720).",
        price: 720,
        rating: 4.8,
        reviews: 260,
        category: "Culture",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=500",
        time: "09:00 AM",
        note: "Medieval lanes, Roman ruins & ancient cathedrals",
        tier: "must",
        icon: "explore"
      },
      {
        id: "bcn-5",
        title: "Flamenco Show at Palau de la Música Catalana",
        description: "Passionate Spanish flamenco dance show featuring guitarists, cantaores, and bailaores inside a spectacular Modernist concert hall (30 EUR ≈ ₹2,700).",
        price: 2700,
        rating: 4.9,
        reviews: 210,
        category: "Culture",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=500",
        time: "08:00 PM",
        note: "Authentic tablao show in a stunning concert hall",
        tier: "popular",
        icon: "theater_comedy"
      },
      {
        id: "bcn-6",
        title: "FC Barcelona Camp Nou Stadium Experience",
        description: "Tour the tunnel, press room, visitor changing rooms, pitch side, and FC Barcelona museum housing Champions League trophies (28 EUR ≈ ₹2,520).",
        price: 2520,
        rating: 4.8,
        reviews: 350,
        category: "Sightseeing",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500",
        time: "10:00 AM",
        note: "Home of FC Barcelona — Europe's largest stadium",
        tier: "popular",
        icon: "sports_soccer"
      },
      {
        id: "bcn-7",
        title: "Barceloneta Mediterranean Beach Walk",
        description: "Relax on golden city sands, stroll W Hotel boardwalk, and sip fresh tinto de verano at oceanfront chiringuito beach bars.",
        price: 0,
        rating: 4.7,
        reviews: 280,
        category: "Water Sports",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500",
        time: "08:00 AM",
        note: "Free beach — paddle boards available to rent",
        tier: "popular",
        icon: "beach_access"
      },
      {
        id: "bcn-8",
        title: "Casa Batlló 10D Immersive Light Show",
        description: "Explore Gaudí's marine dragon house on Passeig de Gràcia with augmented reality smart guide and magical light room (35 EUR ≈ ₹3,150).",
        price: 3150,
        rating: 4.9,
        reviews: 290,
        category: "Culture",
        location: "Barcelona, Spain",
        destination: "Barcelona",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500",
        time: "09:00 PM",
        note: "Gaudí building with immersive 3D projection show at night",
        tier: "extended",
        icon: "palette"
      }
    ]
  },

  Santorini: {
    id: "dest-santorini",
    name: "Santorini",
    country: "Greece",
    countryCode: "GR",
    flag: "🇬🇷",
    region: "Southern Europe",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&auto=format&fit=crop",
    description: "Iconic white-domed cliffs, caldera sunsets & volcanic black beaches.",
    activities: [
      {
        id: "san-1",
        title: "Oia Sunset Blue Dome Viewpoint",
        description: "Watch the world famous golden sunset behind whitewashed cave houses, windmills, and blue-domed Greek Orthodox churches in Oia.",
        price: 0,
        rating: 5.0,
        reviews: 590,
        category: "Sightseeing",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Hourly",
        image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=500",
        time: "06:30 PM",
        note: "World's most photographed sunset — arrive 1 hr early",
        tier: "must",
        icon: "wb_sunny"
      },
      {
        id: "san-2",
        title: "Volcanic Caldera Luxury Catamaran Cruise & BBQ",
        description: "Sail past Nea Kameni volcano, swim in geothermal hot springs, stop at Red Beach and White Beach with Greek wine and seafood BBQ (85 EUR ≈ ₹7,650).",
        price: 7650,
        rating: 5.0,
        reviews: 410,
        category: "Water Sports",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Full-day",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500",
        time: "03:00 PM",
        note: "BBQ, wine, swimming at hot springs & Red Beach stops",
        tier: "must",
        icon: "sailing"
      },
      {
        id: "san-3",
        title: "Cliffside Assyrtiko Wine Tasting Tour",
        description: "Sample crisp volcanic Assyrtiko white wines paired with local graviera cheese and capers at Venetsanos Winery over Caldera views (35 EUR ≈ ₹3,150).",
        price: 3150,
        rating: 4.9,
        reviews: 240,
        category: "Food",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500",
        time: "11:00 AM",
        note: "Volcanic Assyrtiko wine at 3 top island wineries",
        tier: "must",
        icon: "wine_bar"
      },
      {
        id: "san-4",
        title: "Akrotiri Archaeological Minoan Site Tour",
        description: "Explore the ancient 3,600-year-old Bronze Age city preserved beneath volcanic ash, often called Greece's lost city of Atlantis (12 EUR ≈ ₹1,080).",
        price: 1080,
        rating: 4.8,
        reviews: 180,
        category: "Culture",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=500",
        time: "09:00 AM",
        note: "Preserved 3,600-year-old Bronze Age city beneath volcanic ash",
        tier: "popular",
        icon: "account_balance"
      },
      {
        id: "san-5",
        title: "ATV Quad Bike Island Coastal Safari",
        description: "Rent an ATV quad bike to navigate scenic coastal roads from Pyrgos village up to Prophet Elias monastery peak and Perissa (35 EUR ≈ ₹3,150).",
        price: 3150,
        rating: 4.8,
        reviews: 290,
        category: "Adventure",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=500",
        time: "10:00 AM",
        note: "Circle the whole island — Red, White & Black beaches",
        tier: "popular",
        icon: "two_wheeler"
      },
      {
        id: "san-6",
        title: "Fira to Oia Cliffside Crater Rim Hike",
        description: "Breathtaking 10-km walking trail along the edge of the volcanic crater rim connecting Fira, Firostefani, Imerovigli, and Oia.",
        price: 0,
        rating: 4.9,
        reviews: 350,
        category: "Sightseeing",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500",
        time: "09:00 AM",
        note: "10 km coastal trail — 3 hrs with stops for photos",
        tier: "popular",
        icon: "hiking"
      },
      {
        id: "san-7",
        title: "Perissa & Perivolos Black Sand Beach Day",
        description: "Lounge under thatched umbrellas on dark volcanic black sands, swimming in Aegean sea waters with beachside taverna drinks (8 EUR ≈ ₹720).",
        price: 720,
        rating: 4.7,
        reviews: 230,
        category: "Water Sports",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=500",
        time: "10:00 AM",
        note: "Sun loungers available; dramatic black volcanic sand",
        tier: "popular",
        icon: "beach_access"
      },
      {
        id: "san-8",
        title: "Traditional Greek Cooking Class & Farm Lunch",
        description: "Cook classic Greek moussaka, tzatziki, dolmades, and baklava using organic Santorini cherry tomatoes and fava beans (45 EUR ≈ ₹4,050).",
        price: 4050,
        rating: 4.9,
        reviews: 165,
        category: "Food",
        location: "Santorini, Greece",
        destination: "Santorini",
        duration: "Half-day",
        image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500",
        time: "11:00 AM",
        note: "Local home — moussaka, souvlaki & baklava from scratch",
        tier: "extended",
        icon: "school"
      }
    ]
  }
};

// Array of all 80 activities across all 10 cities combined
export const ALL_ACTIVITIES: ActivityItem[] = Object.values(DESTINATION_DATA).flatMap(dest => dest.activities);
